backend:
  name: git-gateway
  branch: main
site_url: https://dbs-headless-poc.netlify.app/
display_url: https://dbs-headless-poc.netlify.app/
media_folder: "src/images"
public_folder: "content/assets"
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
collections:
  - name: "red"
    label: "Red"
    folder: "content/posts/red"
    create: true
    fields:
      - {label: "Make this post featured on the home page?", name: "featured", widget: "boolean", default: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Type", name: "type", widget: "hidden", default: "red"}
  - name: "blue"
    label: "Blue"
    folder: "content/posts/blue"
    create: true
    fields:
      - {label: "Make this post featured on the home page?", name: "featured", widget: "boolean", default: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Type", name: "type", widget: "hidden", default: "blue"}